### ISSUE TITLE
Terminal escape characters and text colour controll

### ISSUE THREAD

**Issue by prying** [imlinhanchao/vsc-serialport-helper#14]
When sending a colour control escape sequence to the terminal it does not print out as expected.

example:
`printf("\033[33mYellow\033[0m\r\n");`
This is printed through the extension as:
![image](https://user-images.githubusercontent.com/20537470/153808802-2a6c1cf9-2e93-4687-a4ba-64b6e157a14a.png)
But i expect this:
![image](https://user-images.githubusercontent.com/20537470/153808904-ad628b60-cb05-43e2-a0a5-a01f0e33f246.png)

**Comment by imlinhanchao** [comment]
That's vscode console log. Not terminal, so it's not support the colour control. I will going to find some other way to support it.

**Comment by prying** [comment]
Cool thanks, i thought that might be the case but though i should bring it up anyway
