### ISSUE TITLE
command 'serialport.refreshEntry' not found

### ISSUE THREAD

**Issue by heartacker** [imlinhanchao/vsc-serialport-helper#15]
![image](https://user-images.githubusercontent.com/1876302/158295844-12b8132c-2e69-4123-915b-aaa375195620.png)

**Comment by heartacker** [comment]
版本: 1.66.0-insider (system setup)
提交: 3e5c7e2c570a729e664253baceaf443b69e82da6
日期: 2022-03-14T05:15:38.097Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22572

名称: Serial Port Helper
ID: hancel.serialport-helper
说明: Serial Port Debug Tool
版本: 0.0.13
发布者: Hancel.Lin
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=hancel.serialport-helper

**Comment by rs-11** [comment]
I have the same issue. Could not found a solution yet. Has anyone solved the problem?

**Comment by YannChansigaud** [comment]
Same issue for me, no solution

**Comment by josephfemia** [comment]
I have also had the same issue.

**Comment by imlinhanchao** [comment]
@rs-11 @YannChansigaud @josephfemia  give me your electron version. You can check it in Help > About .

**Comment by heartacker** [comment]
OK now

**Comment by imlinhanchao** [comment]
@josephfemia update to 0.0.15 will work.

**Comment by josephfemia** [comment]
@imlinhanchao How do I do that?

**Comment by imlinhanchao** [comment]
@josephfemia restart vscode, it will auto update.

**Comment by josephfemia** [comment]
Thank you!!!
