### ISSUE TITLE
vscode1.59 报错

### ISSUE THREAD

**Issue by bjwanghao** [imlinhanchao/vsc-serialport-helper#3]
command ' serialport. refreshEntry' not found  找不到串口

**Comment by imlinhanchao** [comment]
做了什么报这个错？

**Comment by bjwanghao** [comment]
vscode  升级到最新版本   会报错    1.58不会报错

**Comment by imlinhanchao** [comment]
看起来是vscode更新electron版本导致的。我想想看咋搞。

**Comment by DW-CN** [comment]
yes, I encountered the exactly same issue after I upgraded it to v1.59 this morning, thanks for help!

**Comment by bjwanghao** [comment]
新版本是否会添加超级终端模式

**Comment by imlinhanchao** [comment]
超级终端模式是什麽？

**Comment by bjwanghao** [comment]
PuTTY终端串口

**Comment by imlinhanchao** [comment]
是指要可以自己輸入串口號嗎？

VSCode 1.59.0 已經加入支援了。目前只有 Windows. Mac / Linux 還不行。

**Comment by bjwanghao** [comment]
谢谢，可以使用了。终端串口 可以参考https://github.com/makerdiary/terminal-s

**Comment by imlinhanchao** [comment]
> 谢谢，可以使用了。终端串口 可以参考https://github.com/makerdiary/terminal-s

你的這個我不是很理解，是要做成什麽形式？這個看起來是一個終端工具。

**Comment by imlinhanchao** [comment]
> yes, I encountered the exactly same issue after I upgraded it to v1.59 this morning, thanks for help!

The Issue was fixed. But only support windows now. I will update soon to support mac and linux.

**Comment by DW-CN** [comment]
> > yes, I encountered the exactly same issue after I upgraded it to v1.59 this morning, thanks for help!
> 
> @DW-CN The Issue was fixed. But only support windows now. I will update to support mac and linux soon.

Sound good, thanks and waiting....

**Comment by imlinhanchao** [comment]
@DW-CN It's fixed on mac os now.The Linux maybe fixed in weekend.

**Comment by DigitalRogues** [comment]
I'm seeing a similar issue on VS Code 1.60.2 on MacOS.

**Comment by mcusuperuser** [comment]
> @mcusuperuser It's not support in M1.

Ok, understood, thanks!

**Comment by thebino** [comment]
@imlinhanchao Can someone with an M1 device support here? Shouldn't it be possible to cross-compile for M1 as well?

**Comment by thebino** [comment]
Thanks a lot, its working. I think this issue can be closed.

**Comment by mcusuperuser** [comment]
Yes, works like a charm! Thanks for fixing.
