### ISSUE TITLE
serialport.sendEntry by shortcut

### ISSUE THREAD

**Issue by RiKuRail** [imlinhanchao/vsc-serialport-helper#6]
How to specify **port** in keybinding.json? E.g. "COM8"

  {
    "key": "ctrl+backspace",
    "command": "serialport.sendEntry",
    "args":  **???**
  }

**Comment by imlinhanchao** [comment]
You can update to `0.0.12` and setting like this:
```json
{
    "key": "ctrl+backspace",
    "command": "serialport.sendEntry",
    "args": "COM8"
}
```

**Comment by RiKuRail** [comment]
Thanks, works perfect!
